const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const routes=[['CHOOSE','Find the accounts with both upside and urgency.','Rank commercial potential separately from readiness. Look for a stalled implementation, spreadsheet workarounds, a growth trigger or a leader actively looking for a better fit.'],['GET KNOWN','Make the founder’s arrival feel like a continuation.','Map the owner, operations lead and finance voice. Share one relevant observation, useful operator content and a tailored invitation. Give each contact a different reason to care.'],['MEET','Bring their problem into the room.','Coordinate plant visits with pre-booked expo meetings and a small partner-hosted evening. Ask where the current workflow breaks. Leave with a specific discovery commitment.'],['PROVE','Show their workflow, not another generic ERP tour.','After discovery, confirm the inputs for a demo within 72 hours. Offer the 30-day trial with $0 upfront, subject to agreed scope. Track adoption and a real purchase decision.']];
$$('[data-route]').forEach(b=>b.onclick=()=>{$$('[data-route]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});const i=+b.dataset.route,r=routes[i];$('#route-number').textContent=`0${i+1} / ${r[0]}`;$('#route-title').textContent=r[1];$('#route-body').textContent=r[2]});
for(let i=0;i<250;i++){const el=document.createElement('span');el.className='account-dot'+(i%5===0?' priority':'');el.title=`Illustrative account ${i+1}${i%5===0?' / Tier 1':''}`;$('#account-grid').append(el)}
$$('[data-grid]').forEach(b=>b.onclick=()=>{$$('[data-grid]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});$$('.account-dot').forEach(x=>x.classList.toggle('dim',b.dataset.grid==='tier'?!x.classList.contains('priority'):b.dataset.grid==='rest'?x.classList.contains('priority'):false));$('#grid-caption').textContent={all:'50 priority accounts in blue. 200 stay in the wider outreach program.',tier:'50 accounts earn deeper research, physical touches and founder attention.',rest:'200 accounts get lighter digital outreach. Move them up when timing and intent change.'}[b.dataset.grid]});
const depths=[['00','“We already have an ERP.”','Start with what they already use. SimpleGrid sits beside the accounting system and takes on the operational work left in spreadsheets.'],['10','Where does the spreadsheet take over?','Ask about planning, inventory handoffs, costing and exceptions. A system on paper is different from the workflow people actually follow.'],['20','What would make changing worth it?','The owner wants confidence. Operations wants fewer workarounds. Finance needs a credible business case. Validate these motivations rather than assuming them.'],['30','Let them recognise their own operation.','Take one confirmed workflow into discovery. Build the demo around it. Use existing furniture and apparel proof honestly, then validate fit for this plant.']];
$$('[data-depth]').forEach(b=>b.onclick=()=>{$$('[data-depth]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});const d=depths[+b.dataset.depth];$('#depth-marker').textContent=d[0]+' m';$('#depth-title').textContent=d[1];$('#depth-copy').textContent=d[2];$('.dive-window').animate([{opacity:.2,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:document.body.classList.contains('reduced')?0:450})});
const art={book:'<div class="book"><small>AN OPERATOR’S FIELD GUIDE</small><b>Your plant.<br>Your next<br>chapter.</b><span>SIMPLEGRID / PERSONAL EDITION</span></div>',shoe:'<div class="shoe">👟</div>',table:'<div class="table">THE TABLE</div>',signal:'<div class="signal">'+Array.from({length:15},(_,i)=>`<i style="--n:${i}"></i>`).join('')+'</div>',paper:'<div class="postcard"><small>A NOTE FOR YOUR NEXT CHAPTER</small><b>Less chasing.<br>More making.</b></div>',award:'<div class="award"><b>✳</b><span>The people behind the plant.</span></div>',frame:'<div class="frame">⛰</div>',give:'<div class="give"><b>+</b><span>A SMALL GOOD THING</span></div>'};
const plays=[
{title:'The plant field guide',cat:'access',art:'book',desc:'A short, physical account brief worth opening.',hook:'A book for a reader. A useful account story for an operator.',gesture:'Create a compact printed brief: one verified business trigger, one workflow question and a relevant SimpleGrid example. Give it an account-specific cover and QR.',reason:'Show that we understand enough to ask a good question. The content should be useful even if they never take a meeting.',next:'The QR opens a short account page with one discovery invitation. Pilot on a few Tier 1 accounts before printing all 50.'},
{title:'One shoe. One next step.',cat:'access',art:'shoe',desc:'A memorable gesture for a genuinely warm account.',hook:'“We’ve taken the first step. Shall we take the next one together?”',gesture:'For a receptive contact, send a modest single shoe with a handwritten note. Offer the pair without making a meeting a condition.',reason:'A surprising physical reminder can help a warm conversation resurface. This is an optional creative test, not the opening move for every plant.',next:'Use only where the gesture fits the relationship and gifting rules. Compare meeting progression with the simpler printed brief.'},
{title:'The operator’s table',cat:'meet',art:'table',desc:'A small evening that turns a trip into access.',hook:'The best part of the expo may happen after the hall closes.',gesture:'Co-host a small sundowner with a local partner. Invite relevant plant owners and operations leaders around one shared operating problem.',reason:'A trusted host and useful peers make attendance worthwhile. Mukund gets the in-person conversations he prefers.',next:'Agree a practical follow-up with each interested account. Keep the invite list narrow and the event inside the $5,500 allocation.'},
{title:'The voice note, remixed',cat:'access',art:'signal',desc:'A personalised clip, with a reason behind the novelty.',hook:'Twenty seconds to show we actually paid attention.',gesture:'Test a short personalised video, a Cameo-style message or a playful rap for a handful of receptive accounts. Anchor it in a verified business observation.',reason:'A distinctive format can earn the first watch. A relevant operating question earns the reply. Avoid guessing personal details.',next:'One reply request: is this a workflow worth exploring? Use a lower-cost founder clip as the comparison and cap production effort.'},
{title:'A place on the bookshelf',cat:'trust',art:'award',desc:'Give credible operators a platform.',hook:'Make the people who run the factory the story.',gesture:'Launch a small operator interview series, with a roughly ten-episode ambition. Publish useful account spotlights and consider recognition with clear criteria.',reason:'Peer learning can open doors before a sales conversation. Featured people deserve editorial value, not a disguised product endorsement.',next:'Start with two strong interviews. Get permission for quotes and logos. Separate recognition from purchasing and any product claims.'},
{title:'A personal piece of paper',cat:'access',art:'frame',desc:'A hobby-led illustration that feels considered.',hook:'A frame on the desk lasts longer than an attachment.',gesture:'For a known, receptive prospect, commission a tasteful caricature or illustration based on an interest they have publicly shared. Add a short personal note.',reason:'Specificity makes the gesture feel intentional. For Mukund, mountains are a supported reference. Do not apply his interests to other buyers.',next:'Ask for a suitable business delivery address. Keep the price modest and reserve it for a small number of accounts.'},
{title:'The year-end reset',cat:'trust',art:'paper',desc:'A seasonal prompt for the next operating year.',hook:'“What would you stop carrying into next year?”',gesture:'Send a designed postcard with one operational reflection and an account-specific QR. A stocking-themed format can make the seasonal idea tangible.',reason:'The planning period creates a natural reason to revisit persistent workarounds. The business question should carry the message.',next:'If approved, print in early November. Use the $1,500 seasonal allocation; follow up with a useful planning conversation.'},
{title:'A small good thing',cat:'trust',art:'give',desc:'An alternative when gifts would miss the mark.',hook:'Offer consideration without making it transactional.',gesture:'Where appropriate, offer a modest donation to an eligible cause the contact chooses. Keep it independent of any meeting or purchase.',reason:'Some recipients would rather support a cause than receive another object. This is an optional relationship gesture, not an incentive to buy.',next:'Confirm acceptability first. Use transparent amounts and a verifiable receipt. Never imply support from the person without permission.'}
];
const artHTML=p=>`<div class="play-art art-${p.art}" aria-hidden="true">${art[p.art]}</div>`;
function renderPlays(filter='all'){$('#play-grid').innerHTML='';plays.forEach((p,i)=>{if(filter!=='all'&&p.cat!==filter)return;const b=document.createElement('button');b.className='play-card';b.innerHTML=artHTML(p)+`<span class="tag">PLAY ${String(i+1).padStart(2,'0')} / ${p.cat==='access'?'EARN ACCESS':p.cat==='meet'?'MEET IN PERSON':'BUILD FAMILIARITY'}</span><h3>${p.title}</h3><p>${p.desc}</p>`;b.onclick=()=>{$('#dialog-art').innerHTML=artHTML(p);$('#dialog-label').textContent=`THE FIELD GUIDE / PLAY ${i+1}`;$('#dialog-title').textContent=p.title;$('#dialog-hook').textContent=p.hook;$('#dialog-sections').innerHTML=[['THE GESTURE',p.gesture],['WHY IT MATTERS',p.reason],['THE NEXT MOVE',p.next]].map(([h,t])=>`<div><h3>${h}</h3><p>${t}</p></div>`).join('');$('#play-dialog').showModal();document.body.style.overflow='hidden'};$('#play-grid').append(b)})}renderPlays();
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});renderPlays(b.dataset.filter)});
$('#close-dialog').onclick=()=>$('#play-dialog').close();$('#play-dialog').addEventListener('close',()=>document.body.style.overflow='');$('#play-dialog').onclick=e=>{if(e.target===$('#play-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
const budget=[['Expo travel + partner event',5500],['Tier 1 print + gifting',3250],['Seasonal postcards',1500],['Content + creative production',1000],['Data + verification',500],['Tier 2 digital materials',250],['Reserve',500]];
$('#budget-bars').innerHTML=budget.map(([n,v])=>`<div class="budget-line"><div><span>${n}</span><b>$${v.toLocaleString()}</b></div><i><b style="--w:${v/5500*100}%"></b></i></div>`).join('');
$('#wins').oninput=e=>{const n=+e.target.value;$('#wins-number').textContent=n;$('#cac').textContent='$'+Math.round(12500/n).toLocaleString();$('#conversion').textContent=(n/250*100).toFixed(1).replace('.0','')+'%'};
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function motion(){document.body.classList.toggle('reduced',reduced);$('#motion').textContent=reduced?'Motion off':'Motion on';$('#motion').setAttribute('aria-pressed',String(reduced))}motion();$('#motion').onclick=()=>{reduced=!reduced;motion()};
$$('section:not(.hero) h2,.four-metrics,.criteria,.ticket,.execution-grid,.account-grid').forEach(el=>el.classList.add('reveal'));const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
addEventListener('scroll',()=>{$('#progress').style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%'},{passive:true});
const canvas=$('#terrain'),ctx=canvas.getContext('2d');let w,h,px=0,py=0,t=0;function size(){w=canvas.clientWidth;h=canvas.clientHeight;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}size();addEventListener('resize',size);$('.hero').addEventListener('pointermove',e=>{px=(e.clientX/w-.5)*20;py=(e.clientY/h-.5)*12});
function draw(){t+=.003;ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.76,h*.42,0,w*.76,h*.42,w*.55);glow.addColorStop(0,'#244a9540');glow.addColorStop(1,'#07102300');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);for(let layer=0;layer<5;layer++){const base=h*(.55+layer*.11),amp=h*(.28-layer*.025);ctx.beginPath();for(let x=0;x<=w+15;x+=12){const wave=Math.sin(x/w*5.2+layer*.35)*.5+Math.sin(x/w*11.4+layer*.2)*.2+Math.cos(x/w*2.3)*.3;const y=base-wave*amp+py*layer*.13+(reduced?0:Math.sin(t+layer)*4);x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fillStyle=['#101f3d','#152c4d','#19365b','#1b3960','#102c50'][layer];ctx.fill();ctx.strokeStyle='#7899c02c';ctx.lineWidth=1;ctx.stroke();for(let j=1;j<9;j++){ctx.beginPath();for(let x=0;x<=w+15;x+=15){const wave=Math.sin(x/w*5.2+layer*.35)*.5+Math.sin(x/w*11.4+layer*.2)*.2+Math.cos(x/w*2.3)*.3;const y=base-wave*amp+j*10+px*layer*.08;x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle='#a7c8ee0a';ctx.stroke()}}ctx.beginPath();ctx.setLineDash([3,9]);ctx.moveTo(w*.53,h);ctx.bezierCurveTo(w*.95,h*.88,w*.64,h*.67,w*.81,h*.48);ctx.strokeStyle='#95b2ff80';ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(w*.81,h*.48,4,0,Math.PI*2);ctx.fillStyle='#a5baff';ctx.fill();if(!reduced){ctx.beginPath();ctx.arc(w*.81,h*.48,10+Math.sin(t*4)*4,0,Math.PI*2);ctx.strokeStyle='#a5baff50';ctx.stroke()}requestAnimationFrame(draw)}draw();
